/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface IQuadPassportInterface extends ethers.utils.Interface {
  functions: {
    "acceptGovernance()": FunctionFragment;
    "attributes(address,bytes32)": FunctionFragment;
    "balanceOf(address,uint256)": FunctionFragment;
    "balanceOfBatch(address[],uint256[])": FunctionFragment;
    "burnPassports()": FunctionFragment;
    "burnPassportsIssuer(address)": FunctionFragment;
    "passportPaused()": FunctionFragment;
    "setAttributes((bytes32[],bytes32[],bytes32[],bytes32,uint256,uint256,uint256,uint256),bytes,bytes)": FunctionFragment;
    "setAttributesBulk(tuple[],bytes[],bytes[])": FunctionFragment;
    "setAttributesIssuer(address,(bytes32[],bytes32[],bytes32[],bytes32,uint256,uint256,uint256,uint256),bytes)": FunctionFragment;
    "setGovernance(address)": FunctionFragment;
    "setTokenURI(uint256,string)": FunctionFragment;
    "uri(uint256)": FunctionFragment;
    "withdraw(address,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "acceptGovernance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "attributes",
    values: [string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOfBatch",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "burnPassports",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "burnPassportsIssuer",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "passportPaused",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAttributes",
    values: [
      {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      BytesLike,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttributesBulk",
    values: [
      {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      }[],
      BytesLike[],
      BytesLike[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setAttributesIssuer",
    values: [
      string,
      {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setGovernance",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setTokenURI",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "uri", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attributes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOfBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnPassports",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "burnPassportsIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "passportPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttributes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttributesBulk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAttributesIssuer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setGovernance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTokenURI",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "uri", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "BurnPassportsIssuer(address,address)": EventFragment;
    "GovernanceUpdated(address,address)": EventFragment;
    "SetAttributeReceipt(address,address,uint256)": EventFragment;
    "SetPendingGovernance(address)": EventFragment;
    "TransferSingle(address,address,address,uint256,uint256)": EventFragment;
    "URI(string,uint256)": EventFragment;
    "WithdrawEvent(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "BurnPassportsIssuer"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "GovernanceUpdated"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetAttributeReceipt"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "SetPendingGovernance"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TransferSingle"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "URI"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WithdrawEvent"): EventFragment;
}

export type BurnPassportsIssuerEvent = TypedEvent<
  [string, string] & { _issuer: string; _account: string }
>;

export type GovernanceUpdatedEvent = TypedEvent<
  [string, string] & { _oldGovernance: string; _governance: string }
>;

export type SetAttributeReceiptEvent = TypedEvent<
  [string, string, BigNumber] & {
    _account: string;
    _issuer: string;
    _fee: BigNumber;
  }
>;

export type SetPendingGovernanceEvent = TypedEvent<
  [string] & { _pendingGovernance: string }
>;

export type TransferSingleEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber] & {
    operator: string;
    from: string;
    to: string;
    id: BigNumber;
    value: BigNumber;
  }
>;

export type URIEvent = TypedEvent<
  [string, BigNumber] & { value: string; id: BigNumber }
>;

export type WithdrawEventEvent = TypedEvent<
  [string, string, BigNumber] & {
    _issuer: string;
    _treasury: string;
    _fee: BigNumber;
  }
>;

export class IQuadPassport extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: IQuadPassportInterface;

  functions: {
    acceptGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    attributes(
      _account: string,
      _attribute: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      [
        ([string, BigNumber, string] & {
          value: string;
          epoch: BigNumber;
          issuer: string;
        })[]
      ]
    >;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    burnPassports(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    burnPassportsIssuer(
      _account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    passportPaused(overrides?: CallOverrides): Promise<[boolean]>;

    setAttributes(
      _config: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      _sigIssuer: BytesLike,
      _sigAccount: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAttributesBulk(
      _configs: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      }[],
      _sigIssuers: BytesLike[],
      _sigAccounts: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setAttributesIssuer(
      _account: string,
      _config: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      _sigIssuer: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setGovernance(
      _governanceContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    setTokenURI(
      _tokenId: BigNumberish,
      _uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    uri(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    withdraw(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  acceptGovernance(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  attributes(
    _account: string,
    _attribute: BytesLike,
    overrides?: CallOverrides
  ): Promise<
    ([string, BigNumber, string] & {
      value: string;
      epoch: BigNumber;
      issuer: string;
    })[]
  >;

  balanceOf(
    account: string,
    id: BigNumberish,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  balanceOfBatch(
    accounts: string[],
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  burnPassports(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  burnPassportsIssuer(
    _account: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  passportPaused(overrides?: CallOverrides): Promise<boolean>;

  setAttributes(
    _config: {
      attrKeys: BytesLike[];
      attrValues: BytesLike[];
      attrTypes: BytesLike[];
      did: BytesLike;
      tokenId: BigNumberish;
      verifiedAt: BigNumberish;
      issuedAt: BigNumberish;
      fee: BigNumberish;
    },
    _sigIssuer: BytesLike,
    _sigAccount: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAttributesBulk(
    _configs: {
      attrKeys: BytesLike[];
      attrValues: BytesLike[];
      attrTypes: BytesLike[];
      did: BytesLike;
      tokenId: BigNumberish;
      verifiedAt: BigNumberish;
      issuedAt: BigNumberish;
      fee: BigNumberish;
    }[],
    _sigIssuers: BytesLike[],
    _sigAccounts: BytesLike[],
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setAttributesIssuer(
    _account: string,
    _config: {
      attrKeys: BytesLike[];
      attrValues: BytesLike[];
      attrTypes: BytesLike[];
      did: BytesLike;
      tokenId: BigNumberish;
      verifiedAt: BigNumberish;
      issuedAt: BigNumberish;
      fee: BigNumberish;
    },
    _sigIssuer: BytesLike,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setGovernance(
    _governanceContract: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  setTokenURI(
    _tokenId: BigNumberish,
    _uri: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  uri(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

  withdraw(
    _to: string,
    _amount: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    acceptGovernance(overrides?: CallOverrides): Promise<void>;

    attributes(
      _account: string,
      _attribute: BytesLike,
      overrides?: CallOverrides
    ): Promise<
      ([string, BigNumber, string] & {
        value: string;
        epoch: BigNumber;
        issuer: string;
      })[]
    >;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    burnPassports(overrides?: CallOverrides): Promise<void>;

    burnPassportsIssuer(
      _account: string,
      overrides?: CallOverrides
    ): Promise<void>;

    passportPaused(overrides?: CallOverrides): Promise<boolean>;

    setAttributes(
      _config: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      _sigIssuer: BytesLike,
      _sigAccount: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setAttributesBulk(
      _configs: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      }[],
      _sigIssuers: BytesLike[],
      _sigAccounts: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    setAttributesIssuer(
      _account: string,
      _config: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      _sigIssuer: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    setGovernance(
      _governanceContract: string,
      overrides?: CallOverrides
    ): Promise<void>;

    setTokenURI(
      _tokenId: BigNumberish,
      _uri: string,
      overrides?: CallOverrides
    ): Promise<void>;

    uri(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<string>;

    withdraw(
      _to: string,
      _amount: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "BurnPassportsIssuer(address,address)"(
      _issuer?: string | null,
      _account?: string | null
    ): TypedEventFilter<
      [string, string],
      { _issuer: string; _account: string }
    >;

    BurnPassportsIssuer(
      _issuer?: string | null,
      _account?: string | null
    ): TypedEventFilter<
      [string, string],
      { _issuer: string; _account: string }
    >;

    "GovernanceUpdated(address,address)"(
      _oldGovernance?: string | null,
      _governance?: string | null
    ): TypedEventFilter<
      [string, string],
      { _oldGovernance: string; _governance: string }
    >;

    GovernanceUpdated(
      _oldGovernance?: string | null,
      _governance?: string | null
    ): TypedEventFilter<
      [string, string],
      { _oldGovernance: string; _governance: string }
    >;

    "SetAttributeReceipt(address,address,uint256)"(
      _account?: string | null,
      _issuer?: string | null,
      _fee?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _account: string; _issuer: string; _fee: BigNumber }
    >;

    SetAttributeReceipt(
      _account?: string | null,
      _issuer?: string | null,
      _fee?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _account: string; _issuer: string; _fee: BigNumber }
    >;

    "SetPendingGovernance(address)"(
      _pendingGovernance?: string | null
    ): TypedEventFilter<[string], { _pendingGovernance: string }>;

    SetPendingGovernance(
      _pendingGovernance?: string | null
    ): TypedEventFilter<[string], { _pendingGovernance: string }>;

    "TransferSingle(address,address,address,uint256,uint256)"(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      id?: null,
      value?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        operator: string;
        from: string;
        to: string;
        id: BigNumber;
        value: BigNumber;
      }
    >;

    TransferSingle(
      operator?: string | null,
      from?: string | null,
      to?: string | null,
      id?: null,
      value?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        operator: string;
        from: string;
        to: string;
        id: BigNumber;
        value: BigNumber;
      }
    >;

    "URI(string,uint256)"(
      value?: null,
      id?: BigNumberish | null
    ): TypedEventFilter<[string, BigNumber], { value: string; id: BigNumber }>;

    URI(
      value?: null,
      id?: BigNumberish | null
    ): TypedEventFilter<[string, BigNumber], { value: string; id: BigNumber }>;

    "WithdrawEvent(address,address,uint256)"(
      _issuer?: string | null,
      _treasury?: string | null,
      _fee?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _issuer: string; _treasury: string; _fee: BigNumber }
    >;

    WithdrawEvent(
      _issuer?: string | null,
      _treasury?: string | null,
      _fee?: null
    ): TypedEventFilter<
      [string, string, BigNumber],
      { _issuer: string; _treasury: string; _fee: BigNumber }
    >;
  };

  estimateGas: {
    acceptGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    attributes(
      _account: string,
      _attribute: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    burnPassports(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    burnPassportsIssuer(
      _account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    passportPaused(overrides?: CallOverrides): Promise<BigNumber>;

    setAttributes(
      _config: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      _sigIssuer: BytesLike,
      _sigAccount: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAttributesBulk(
      _configs: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      }[],
      _sigIssuers: BytesLike[],
      _sigAccounts: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setAttributesIssuer(
      _account: string,
      _config: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      _sigIssuer: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setGovernance(
      _governanceContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    setTokenURI(
      _tokenId: BigNumberish,
      _uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    uri(_tokenId: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    withdraw(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    acceptGovernance(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    attributes(
      _account: string,
      _attribute: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOf(
      account: string,
      id: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    balanceOfBatch(
      accounts: string[],
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    burnPassports(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    burnPassportsIssuer(
      _account: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    passportPaused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setAttributes(
      _config: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      _sigIssuer: BytesLike,
      _sigAccount: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAttributesBulk(
      _configs: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      }[],
      _sigIssuers: BytesLike[],
      _sigAccounts: BytesLike[],
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setAttributesIssuer(
      _account: string,
      _config: {
        attrKeys: BytesLike[];
        attrValues: BytesLike[];
        attrTypes: BytesLike[];
        did: BytesLike;
        tokenId: BigNumberish;
        verifiedAt: BigNumberish;
        issuedAt: BigNumberish;
        fee: BigNumberish;
      },
      _sigIssuer: BytesLike,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setGovernance(
      _governanceContract: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    setTokenURI(
      _tokenId: BigNumberish,
      _uri: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    uri(
      _tokenId: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    withdraw(
      _to: string,
      _amount: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
