/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface TestQueryUtilsInterface extends ethers.utils.Interface {
  functions: {
    "CountryIsEqual(bytes32,string)": FunctionFragment;
    "IsBusinessFalse(bytes32)": FunctionFragment;
    "IsBusinessTrue(bytes32)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "CountryIsEqual",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "IsBusinessFalse",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "IsBusinessTrue",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "CountryIsEqual",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IsBusinessFalse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IsBusinessTrue",
    data: BytesLike
  ): Result;

  events: {};
}

export class TestQueryUtils extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: TestQueryUtilsInterface;

  functions: {
    CountryIsEqual(
      _attrValue: BytesLike,
      _expectedString: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    IsBusinessFalse(
      _attrValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    IsBusinessTrue(
      _attrValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  CountryIsEqual(
    _attrValue: BytesLike,
    _expectedString: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  IsBusinessFalse(
    _attrValue: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  IsBusinessTrue(
    _attrValue: BytesLike,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    CountryIsEqual(
      _attrValue: BytesLike,
      _expectedString: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    IsBusinessFalse(
      _attrValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;

    IsBusinessTrue(
      _attrValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    CountryIsEqual(
      _attrValue: BytesLike,
      _expectedString: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    IsBusinessFalse(
      _attrValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    IsBusinessTrue(
      _attrValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    CountryIsEqual(
      _attrValue: BytesLike,
      _expectedString: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    IsBusinessFalse(
      _attrValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    IsBusinessTrue(
      _attrValue: BytesLike,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
